Fixing empty bug
googleinterns/step59-2020 pull request #21
Opened 2020-08-05 14:58 UTC by John42506176Linux

DONT LOOK AT THIS PR Until CLoud Functions Update gets approved and merged.
This is to mainly to fix a problem with tickers returning null occasionally. The database was shortened because of it. No screenshot because it's not a visual change.

2020-08-06 14:51 UTC, asam01 requested changes
left some comments

2020-08-06 14:51 UTC, asam01 commented on src/components/firebase-access.jsx
> -      console.log(response); // This is here until the next pr gets approved.
can you set all this stuff back to what it was on master?

2020-08-06 14:51 UTC, asam01 commented on src/components/firebase-access.jsx
> -      console.log(response); // Same as above
also set this back to align with master

2020-08-06 14:51 UTC, asam01 commented on src/components/firebase-access.jsx
>            },100000)
also restore to master version

2020-08-06 14:51 UTC, asam01 commented on src/components/pages/Host.jsx
> +            prices: null,
why does the host need to store images and prices?

2020-08-06 14:51 UTC, asam01 commented on stock_backend/StoreTickerData.py
> +NYSE =  pd.read_csv("companylistNYSE.csv")
what is all of this stuff that's commented out?

2020-08-06 14:51 UTC, asam01 commented on stock_backend/StoreTickerData.py
> +        num+=1
keep indentation consistent. this is 8 spaces - before, you used 4

2020-08-06 18:17 UTC, John42506176Linux commented
The 6000 lines is because I added the csv files to the commit, its around 200-300 lines of code

2020-08-06 18:17 UTC, John42506176Linux commented
I also added the gray out button to the commit just to make i simple.

2020-08-06 18:59 UTC, asam01 reviewed
lgtm, can you just fix the try/catch style to include a space after try?

`try {`

2020-08-06 19:03 UTC, asam01 approved these changes

2020-08-06 19:45 UTC, yukyhaha commented on src/components/firebase-access.jsx
> +      }
what if some other error code returned?

2020-08-07 22:01 UTC, yukyhaha approved these changes

2020-08-07 23:09 UTC, merged